[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "sameorigin"
    X-XSS-Protection = "1; mode=block"
    Content-Security-Policy = "default-src 'none'; font-src 'https://fonts.googleapis.com'; img-src 'self' https://i.imgur.com; object-src 'none'; script-src 'self'; style-src 'self'"